# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b92c00baad2f81962b3190c3f225a29b"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Boost"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
